services:
  webserver:
    image: fnagel/docker-typo3-webserver-dev:${DOCKER_PHP_TAG}
    container_name: '${COMPOSE_PROJECT_NAME}-webserver'
    build:
      context: ./dev
      args:
        php_tag: ${DOCKER_PHP_TAG}
        composer_tag: ${DOCKER_COMPOSER_TAG}
        nodejs_tag: ${DOCKER_NODEJS_TAG}
        docker_image: "fnagel/docker-typo3-webserver"
    environment:
      - TYPO3_CONTEXT=Development
    networks:
      - mailhog

  db:
    container_name: '${COMPOSE_PROJECT_NAME}-db'

  adminer:
    image: adminer
    container_name: '${COMPOSE_PROJECT_NAME}-adminer'
    ports:
      - 8080:8080
    networks:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: '${COMPOSE_PROJECT_NAME}-mailhog'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - mailhog

networks:
  mailhog:
